
[scrobbler]
user_id = 8834263
mode = "osu"
use_original_metadata = true
min_beatmap_length_secs = 60
scrobble_fails = false
log_scrobbles = false
artist_redirects = []
artist_regex_redirects = []
title_regex_redirects = []

[scrobbler.blacklist.artists]
equals = []
contains_words = []
matches_regex = []

[scrobbler.blacklist.titles]
equals = []
contains_words = []
matches_regex = []

[scrobbler.blacklist.difficulties]
equals = []
contains_words = []
matches_regex = []

[last_fm]
username = "..."
password = "..."
api_key = "..."
api_secret = "..."

# [listenbrainz]
# user_token = "..."
