#
# (required) The scrobbler configuration
#
[scrobbler]

# (required) Your osu! user ID
user_id = 8834263

# The osu! mode to scrobble. Possible values: "osu", "taiko", "fruits", "mania" (default: user's default mode)
mode = "osu"

# Whether to use original metadata instead of romanized metadata (default: true)
use_original_metadata = true

# The minimum beatmap length to scrobble (in seconds) (default: 60)
min_beatmap_length_secs = 60

# Whether to scrobble failed plays. On osu!lazer, the failed duration must at least be 50% of the entire beatmap or 4 minutes (default: false)
scrobble_fails = true

# Whether to log scrobbles to a file (default: false)
log_scrobbles = false

# A list of tuples that contain the old and new artist name to replace with before scrobbling (case-insensitive)
artist_redirects = [["96çŒ«", "Kuroneko"]]

# A list of tuples that contain a regex pattern and replacer string to replace artists with before scrobbling (case-sensitive)
artist_regex_redirects = [["(.+) \\(?feat\\. (.+)\\)?", "$1"]]

# A list of tuples that contain a regex pattern and replacer string to replace artists with before scrobbling (case-sensitive)
title_regex_redirects = [
	[
		"(.+) \\(?feat\\. (.+)\\)?",
		"$1",
	],
	[
		"(.+) (?i:\\(TV Size\\))",
		"$1",
	],
]

#
# Artists to blacklist from scrobbling
#
[scrobbler.blacklist.artists]

# A list of artists to blacklist (case-insensitive)
equals = []

# A list of words inside an artist to blacklist (case-insensitive)
contains_words = []

# A list of regex pattern strings to blacklist (case-sensitive)
matches_regex = []

#
# Titles to blacklist from scrobbling
#
[scrobbler.blacklist.titles]

# A list of titles to blacklist (case-insensitive)
equals = []

# A list of words inside a title to blacklist (case-insensitive)
contains_words = []

# A list of regex pattern strings to blacklist (case-sensitive)
matches_regex = []

#
# Difficulties to blacklist from scrobbling
#
[scrobbler.blacklist.difficulties]

# A list difficulties to blacklist (case-insensitive)
equals = []

# A list of words inside a difficulty to blacklist (case-insensitive)
contains_words = []

# A list of regex pattern strings to blacklist (case-sensitive)
matches_regex = []

#
# (required) The Last.fm configuration. Optional if you're already using at least one other scrobbler
#
[last_fm]

# (required) Your Last.fm username
username = "..."

# (required) Your Last.fm password
password = "..."

# (required) # Your Last.fm API key
api_key = "..."

# (required) Your Last.fm API secret
api_secret = "..."

#
# (required) The ListenBrainz configuration. Optional if you're already using at least one other scrobbler
#
[listenbrainz]

# (required) Your ListenBrainz user token
user_token = "..."
