#
# (required) The scrobbler configuration
#
[scrobbler]

# Your osu! user ID
user_id = 8834263

# (optional) The osu! mode to scrobble. Possible values: "osu", "taiko", "fruits", "mania" (default: user's default mode)
mode = "osu"

# (optional) Whether to use original metadata instead of romanized metadata (default: true)
use_original_metadata = true

# (optional) The minimum beatmap length to scrobble (in seconds) (default: 60)
min_beatmap_length_secs = 60

# (optional) Whether to scrobble failed plays. On osu!lazer, the failed duration must at least be 50% of the entire beatmap or 4 minutes (default: false)
scrobble_fails = true

# (optional) Whether to log scrobbles to a file (default: false)
log_scrobbles = false

# (optional) A list of tuples that contain the old and new artist name to replace with before scrobbling (case-insensitive)
artist_redirects = [["old artist", "new artist"]]

#
# (optional) Artists to blacklist from scrobbling
#
[scrobbler.blacklist.artists]

# (optional) A list of equal matches to blacklist inside an artist (case-insensitive)
equals = []

# (optional) A list of artists to blacklist (case-insensitive)
contains_word = []

#
# (optional) Titles to blacklist from scrobbling
#
[scrobbler.blacklist.titles]

# (optional) A list of equal matches to blacklist inside a title (case-insensitive)
equals = []

# (optional) A list of titles blacklist (case-insensitive)
contains_word = []

#
# (optional) Difficulties to blacklist from scrobbling
#
[scrobbler.blacklist.difficulties]

# (optional) A list difficulties to blacklist (case-insensitive)
equals = []

# (optional) A list of keywords to blacklist inside a difficulty (case-insensitive)
contains_word = []

#
# The Last.fm configuration. Optional to omit if you're already using at least one other scrobbler
#
[last_fm]

# (required) Your Last.fm username
username = "username" # Your Last.fm username

# (required) Your Last.fm password
password = "password"

# (required) # Your Last.fm API key
api_key = "api_key"

# (required) Your Last.fm API secret
api_secret = "api_secret"

#
# The ListenBrainz configuration. Optional to omit if you're already using at least one other scrobbler
#
[listenbrainz]

# (required) Your ListenBrainz user token
user_token = "user_token"
