[scrobbler]
user_id = 8834263
mode = "default"
use_original_metadata = true
min_beatmap_length_secs = 60
scrobble_fails = false
log_scrobbles = false

[scrobbler.redirects.artists]
equal_matches = []
regex_matches = []

[scrobbler.redirects.titles]
equal_matches = []
regex_matches = []

[scrobbler.blacklist.artists]
equal_matches = []
regex_matches = []

[scrobbler.blacklist.titles]
equal_matches = []
regex_matches = []

[scrobbler.blacklist.difficulties]
equal_matches = []
regex_matches = []

[last_fm]
username = "..."
password = "..."
api_key = "..."
api_secret = "..."

# [listenbrainz]
# user_token = "..."
